### ISSUE TITLE
moulin: can't add multiple args as array for custom scrip builder

### ISSUE THREAD

**Issue by al1img** [xen-troops/moulin#100]
I expect args could be added as string array, similar to args in `bazel` builder:

```sh
  args:
    - "--arg1"
    - "--arg2"
```

But I have error in this case:

```sh
moulin.yaml_helpers.YAMLProcessingError: Expected string value, got <class 'NoneType'>   in "secure-rpi.yaml", line 93, column 9
ninja: error: rebuilding 'build.ninja': subcommand failed
```

Only args as string is allowed:

```sh
args "--arg1 --arg2"
```

that is not convenient for long args string.

**Comment by dsemenets** [comment]
Created PR https://github.com/xen-troops/moulin/pull/103

**Comment by dsemenets** [comment]
@al1img I guess this issue can be closed
