### ISSUE TITLE
rouge: possibility to specify in-image offset for some files

### ISSUE THREAD

**Issue by rshym** [xen-troops/moulin#52]
In some cases, we may need to put the binary file at a specific offset inside the image, outside of partitions.

**Comment by lorc** [comment]
Is this a duplicate of #26 ?

**Comment by rshym** [comment]
Unfortunately, I do not remember exactly. I remember that we had a small session with writing down all desired features, and possibly, this relates to some situation with loaders on the IMX platform, where the loader should be placed in a specific offset. But I do not remember exactly.
So, maybe it's OK to close this issue because it's not clear now what it means.
