### ISSUE TITLE
moulin: support network URL for yaml

### ISSUE THREAD

**Issue by rshym** [xen-troops/moulin#54]
For now, moulin supports only local files as build description.
It could be very convenient to specify `build.yaml` by URL.

**Comment by rshym** [comment]
Need to discuss which type of URL we should support.
List possible cases:
1. raw content on github `https://raw.githubusercontent.com/xen-troops/meta-xt-prod-devel-rcar/master/prod-devel-rcar.yaml`
2. github page `https://github.com/xen-troops/meta-xt-prod-devel-rcar/blob/master/prod-devel-rcar.yaml`
3. A la repo style `-u url -b branch -m name`
4. Something other?

Should we just download build.yaml locally once or re-download it each time?

**Comment by lorc** [comment]
1. For sure
2. Would be good, but is not strictly required
3. This implies dependency on git, I don't think I need this.

> Should we just download build.yaml locally once or re-download it each time?

Download once and refuse to overwrite existing file. I prefer "least surprise" approach.

**Comment by rshym** [comment]
PR is merged.
