### ISSUE TITLE
moulin: add possibility to set CMAKE variable for zephyr builder

### ISSUE THREAD

**Issue by al1img** [xen-troops/moulin#70]
In zephyr I can specify cmake variables using west as following:
```
west build -b board -p always -- -DCONFIG_VAR1=val1 -DCONFIG_VAR2=val2
```
We need this possibility to adjust some configuration depends on board, variables etc.

**Comment by lorc** [comment]
Hi @al1img,

have you checked #62 ?

I believe, this is what you want.

**Comment by al1img** [comment]
Unfortunately, nope. 

```
CONFIG_VAR1=val1 && west build -b board
```

not the same as

```
west build -b board  -- -DCONFIG_VAR1=val1
```

**Comment by lorc** [comment]
I see.

How urgent it is? I can prepare a patch, but I need someone to test it.

**Comment by al1img** [comment]
Not blocker but nice to have. I can't test it.

**Comment by dsemenets** [comment]
There is PR https://github.com/xen-troops/moulin/pull/71
Will be merged soon

**Comment by al1img** [comment]
It doesn't work for me.

I'm addition the following variables:

```
vars:
    - "CONFIG_AOS_NODE_ID=%{GEN4_DOM0_NODE_ID}"
    - "CONFIG_AOS_NODE_TYPE=%{GEN4_DOM0_NODE_TYPE}"
```

**Comment by dsemenets** [comment]
Here is problem of quotes. String constants in config should be in quotes bun quotes used in other things like ninja, shell. So quotes should be shielded with backslash. Backslash should be shielded with backslash etc. Actually working configuration:

```
vars:                                                                                                    
 - "CONFIG_AOS_NODE_ID=\\\\\\\"%{GEN4_DOM0_NODE_ID}\\\\\\\""                                                                                                                           
 - "CONFIG_AOS_NODE_TYPE=\\\\\\\"%{GEN4_DOM0_NODE_TYPE}\\\\\\\""
```
I agree it looks ugly... but works
