### ISSUE TITLE
It is impossible to pass a BASH variable with "" to the underneath build systems

### ISSUE THREAD

**Issue by arminn** [xen-troops/moulin#80]
Unable to pass variable like

EXT_MODULES="
AAA
BBB
CCC
DDD
"
to underneath build system

**Comment by arminn** [comment]
Example:
let's imagine that we are using android kernel builder like: https://github.com/xen-troops/meta-xt-prod-cockpit-rcar/blob/master/prod-cockpit-rcar.yaml#L254

there is possibility to pass env variables to android kernel build system like : https://github.com/xen-troops/meta-xt-prod-cockpit-rcar/blob/master/prod-cockpit-rcar.yaml#L267

It is impossible to pass env variable like: https://github.com/xen-troops/linux/blob/common-android13-5.10-xt-cr7/build.config.xenvm.no_graphics#L11C1-L16C2

i.e. 

EXT_MODULES="
modules/vspm
modules/vspmif
modules/mmngr
modules/uvcs
"

**Comment by lorc** [comment]
Fixed with #83
