### ISSUE TITLE
moulin: add fetcher for custom script builder

### ISSUE THREAD

**Issue by al1img** [xen-troops/moulin#99]
My custom scripts are located and some repo. I would like to fetch them before execution. `source` node doesn't work for custom build builder.

**Comment by lorc** [comment]
Yeah, this is the problem with custom scripts. AFAIK, current approach is to get the `.yaml` file along with all the custom scripts by cloning a git repo or downloading an archive.

**Comment by dsemenets** [comment]
Created PR https://github.com/xen-troops/moulin/pull/104
